# Generated by Django 5.2.14 on 2026-05-29 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('STYLE', 'Sightseeing Style'), ('TASTE', 'Taste Preference')], max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hygiene_sensitivity', models.IntegerField(blank=True, null=True)),
                ('preparedness', models.IntegerField(blank=True, null=True)),
                ('choices', models.ManyToManyField(blank=True, to='accounts.preferencechoice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
